### ISSUE TITLE
Error running safe auth install

### ISSUE THREAD

**Issue by Folaht** [maidsafe/sn_api#655]
version: sn_cli 0.16 linux unknown binary
OS: Manjaro linux

```plain
$ RUST_BACKTRACE=1 safe auth install
thread 'main' panicked at 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.', /home/folaht/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/blocking/shutdown.rs:51:21
stack backtrace:
   0: std::panicking::begin_panic
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:505
   1: tokio::runtime::blocking::shutdown::Receiver::wait
             at /home/folaht/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/blocking/shutdown.rs:51
   2: tokio::runtime::blocking::pool::BlockingPool::shutdown
             at /home/folaht/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/blocking/pool.rs:138
   3: <tokio::runtime::blocking::pool::BlockingPool as core::ops::drop::Drop>::drop
             at /home/folaht/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/blocking/pool.rs:148
   4: core::ptr::drop_in_place
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
   5: core::ptr::drop_in_place
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ptr/mod.rs:175
   6: reqwest::blocking::wait::enter
             at /home/folaht/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.9/src/blocking/wait.rs:74
   7: reqwest::blocking::wait::timeout
             at /home/folaht/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.9/src/blocking/wait.rs:14
   8: reqwest::blocking::client::ClientHandle::new
             at /home/folaht/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.9/src/blocking/client.rs:794
   9: reqwest::blocking::client::ClientBuilder::build
             at /home/folaht/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.9/src/blocking/client.rs:96
  10: reqwest::blocking::client::Client::new
             at /home/folaht/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.10.9/src/blocking/client.rs:601
  11: self_update::backends::s3::fetch_releases_from_s3
             at /home/folaht/.cargo/registry/src/github.com-1ecc6299db9ec823/self_update-0.15.0/src/backends/s3.rs:466
  12: <self_update::backends::s3::Update as self_update::update::ReleaseUpdate>::get_latest_release
             at /home/folaht/.cargo/registry/src/github.com-1ecc6299db9ec823/self_update-0.15.0/src/backends/s3.rs:363
  13: safe::operations::helpers::download_and_install_bin
             at /home/folaht/safe/sn_api/sn_cli/operations/helpers.rs:51
  14: safe::operations::helpers::download_from_s3_and_install_bin
             at /home/folaht/safe/sn_api/sn_cli/operations/helpers.rs:40
  15: safe::operations::auth_daemon::authd_install
             at /home/folaht/safe/sn_api/sn_cli/operations/auth_daemon.rs:45
  16: safe::subcommands::auth::auth_commander::{{closure}}
             at /home/folaht/safe/sn_api/sn_cli/subcommands/auth.rs:190
  17: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/future/mod.rs:80
  18: safe::cli::run_with::{{closure}}
             at /home/folaht/safe/sn_api/sn_cli/cli.rs:116
  19: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/future/mod.rs:80
  20: safe::cli::run::{{closure}}
             at /home/folaht/safe/sn_api/sn_cli/cli.rs:55
  21: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/future/mod.rs:80
  22: safe::main::{{closure}}
             at /home/folaht/safe/sn_api/sn_cli/main.rs:40
  23: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/future/mod.rs:80
  24: tokio::runtime::enter::Enter::block_on::{{closure}}
             at /home/folaht/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/enter.rs:160
  25: tokio::coop::with_budget::{{closure}}
             at /home/folaht/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/coop.rs:127
  26: std::thread::local::LocalKey<T>::try_with
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/thread/local.rs:272
  27: std::thread::local::LocalKey<T>::with
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/thread/local.rs:248
  28: tokio::coop::with_budget
             at /home/folaht/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/coop.rs:120
  29: tokio::coop::budget
             at /home/folaht/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/coop.rs:96
  30: tokio::runtime::enter::Enter::block_on
             at /home/folaht/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/enter.rs:160
  31: tokio::runtime::thread_pool::ThreadPool::block_on
             at /home/folaht/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/thread_pool/mod.rs:82
  32: tokio::runtime::Runtime::block_on::{{closure}}
             at /home/folaht/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/mod.rs:446
  33: tokio::runtime::context::enter
             at /home/folaht/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/context.rs:72
  34: tokio::runtime::handle::Handle::enter
             at /home/folaht/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/handle.rs:76
  35: tokio::runtime::Runtime::block_on
             at /home/folaht/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-0.2.24/src/runtime/mod.rs:441
  36: safe::main
             at /home/folaht/safe/sn_api/sn_cli/main.rs:34
  37: core::ops::function::FnOnce::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by enricop** [comment]
Hello, i have the same issue on ArchLinux

I have compiled sn_cli with "cargo build" and than run "./safe auth install"

```
name = 'sn_cli'
operating_system = 'unix:Arch'
crate_version = '0.23.3'
explanation = '''
Panic occurred in file '/home/sunkiss/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/blocking/shutdown.rs' at line 51
'''
cause = 'Cannot drop a runtime in a context where blocking is not allowed. This happens when a runtime is dropped from within an asynchronous context.'
method = 'Panic'
backtrace = '''

   0: 0x558cc2af914c - tokio::runtime::blocking::pool::BlockingPool::shutdown::h598320174bef9a56
                at /home/sunkiss/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/blocking/pool.rs:158
   1: 0x558cc2af974c - <tokio::runtime::blocking::pool::BlockingPool as core::ops::drop::Drop>::drop::h5f466753b0530dcc
                at /home/sunkiss/.cargo/registry/src/github.com-1ecc6299db9ec823/tokio-1.5.0/src/runtime/blocking/pool.rs:175
   2: 0x558cc2af4926 - core::ptr::drop_in_place<tokio::runtime::blocking::pool::BlockingPool>::hd871186c05836531
                at /build/rust/src/rustc-1.51.0-src/library/core/src/ptr/mod.rs:179
   3: 0x558cc2af33b6 - core::ptr::drop_in_place<tokio::runtime::Runtime>::hd69225540b4ee004
                at /build/rust/src/rustc-1.51.0-src/library/core/src/ptr/mod.rs:179
   4: 0x558cc165983e - reqwest::blocking::wait::enter::hc56a73e43b9b3612
                at /home/sunkiss/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.3/src/blocking/wait.rs:76
   5: 0x558cc1656400 - reqwest::blocking::wait::timeout::h72ae8f4682dfdb9a
                at /home/sunkiss/.cargo/registry/src/github.com-1ecc6299db9ec823/reqwest-0.11.3/src/blocking/wait.rs:13
```

how did you solved? thank you

**Comment by Folaht** [comment]
Maidsafe does not yet have aarch64 binaries yet.
You have to compile them from source.

**Comment by enricop** [comment]
hello, 
I didn't tried precompiled x86_64 binaries. I would like to compile from source. I'm on a x86_64 system.
I just followed these steps:
```
$ git clone https://github.com/maidsafe/sn_api.git
$ cd sn_api
$ cargo build
$ cd target/debug
$ ./safe auth install
```
were you able to compile from source on x86_64 Arch Linux derived distros?

**Comment by Folaht** [comment]
No, I think think I got confused with Arch linux, aarch64 architecture and a issue I had due to not running the correct architecture.
